### ISSUE TITLE
API Key Generator Down

### ISSUE THREAD

**Issue by jakenathanson** [kraigh/serverless-todo-api#2]
Hello, 
I hope all is well. The API Key Generator site https://cse204.kraigh.net/api-key cannot be reached. 
There is a Response of ERR_TIMED_OUT. I have checked this issues with multiple devices. Thanks so much! I hope you feel better. 
Best,
Jake

**Comment by jakenathanson** [comment]
I think I just figured out the issue. The issue is that the docs links to a https version but it can only be served on http. Link should be changed to http://cse204.kraigh.net/api-key/ Thanks!

**Comment by kraigh** [comment]
Good catch. Instead of changing the links i'm going to enable HTTPS on the page (and all of the documentation) by adding a CloudFront distribution in front of the S3 bucket that serves the page.

Waiting on the CloudFront to finish deploying, and then i'll update DNS to point cse204.kraigh.net to it instead of the bucket directly.

**Comment by jakenathanson** [comment]
Thank you so much. That makes sense.  I appreciate it.

**Comment by jakenathanson** [comment]
I think CloudFront CDN may have possibly cached the old site and may not be the current static build. I fixed the mixed content error caused by the move over to https. Thanks!
